name: Nightly
on:
  workflow_dispatch:
  #schedule:
    #- cron: '05 08 * * *'   #Runs at 08:05 UTC  https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    #- cron: '5 14,20 7 5 0' #Runs at 14:05 and 20:05, on day 7 of the month, and on Sunday, only in May. UTC (Two triggers: specific date, the day of the week)
    #- cron: '5 02,08 8 5 *' #Runs at 02:05 and 08:05, on day 8 of the month, only in May. UTC (One trigger: specific date)
    #- cron: '10 18 5 5 5'
    #- cron: '15 0,6,12,18 6 5 6'

jobs:
  Nightly-src:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pre (show dev-info)
        run: |
          printf 'Processor: '; cat /proc/cpuinfo|grep processor|wc -l
          cat /proc/cpuinfo|grep 'model name'|head -1; echo
          cat /proc/meminfo | head
          echo; uname -a
          echo; swapon -v
        shell: bash -e {0}

      - name: Get Sources
        run: |
          aria2c -x16 -s16 https://hg.mozilla.org/mozilla-central/archive/tip.zip -o firefox-nightly.zip
          unzip -q firefox-nightly.zip
          mv mozilla-central-???????????? nightly -v
          echo ' '
          cat nightly/browser/config/version.txt
        shell: bash -e {0}

      - name: Build
        run: |
          echo "::Building  firefox-nightly sources package..."; sudo chown $(id -u):$(id -g) -R /mnt
          name="$(date -u +%Y%m%d)-$(<nightly/browser/config/version.txt)-nightly"; (cd nightly; tar cf - .|xz -T0) >/mnt/$name.tar.xz
          (cd /mnt; ls -lh *.tar.xz); free -h
          echo ' '; df -h
        shell: bash -e {0}

      - name: Upload
        run: |
          name="$(date -u +%Y%m%d)-$(<nightly/browser/config/version.txt)-nightly"
          mv /mnt/$name.tar.xz .
          bash -e pushGit "$name.tar.xz"
        shell: bash -e {0}
